### ISSUE TITLE
xmind好像不好使

### ISSUE THREAD

**Issue by songpf888** [qy527145/crack#1]
xmind好像不好使

**Comment by kurtscoder** [comment]
确实，好像有问题，提示激活成功，但是实际却没有成功，一直提示升级只pro
![image](https://github.com/qy527145/crack/assets/154317089/6b3baa73-ffe7-483c-8303-053ad9e926a0)

**Comment by AndroidDreaming** [comment]
附议，同样的日志输出，实际上没有效果。

**Comment by qy527145** [comment]
需要升级一下crypto_plus依赖（1.0.1，1.0.2两个版本会有该问题）
原因请看[这里](https://linux.do/t/topic/30574/60?u=wmymz)
